---
language: ruby
cache: bundler

script: bundle exec rake test

rvm:
  - 2.3
  - 2.7
  - jruby-9.2.9.0
  - truffleruby
  - ruby-head
  - jruby-head
  
matrix:
  include:
    - name: benchmark
      rvm: 2.7
      script: bundle exec benchmark-driver benchmark/bitcount.yml --rvm 2.7
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby