---
language: ruby
cache: bundler

script: bundle exec rake test

rvm:
  - 2.3
  - 2.7
  - jruby-9.2.9.0
  - truffleruby
  - ruby-head
  - jruby-head
  
matrix:
  include:
    - name: benchmark-ruby
      rvm: 2.7
      script:
        - bundle exec rake compile:bitcount_ext
        - bundle exec ruby -S benchmark-driver benchmark/bitcount.yml
    - name: benchmark-jruby
      rvm: jruby-head
      script:
        - bundle exec rake compile:bitcount_ext
        - bundle exec ruby -S benchmark-driver benchmark/bitcount.yml
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby
    - name: benchmark-ruby
    - name: benchmark-jruby